language: ruby
cache:
- bundler
rvm:
- 2.5.1
before_script:
- cp config/database.travis.yml config/database.yml
- bundle exec rake db:create
- bundle exec rake db:migrate
- bundle exec rake assets:precompile
script:
- bundle exec rake ci:tests
services:
- postgresql
notifications:
  email: false
env:
  global:
    secure: pGGNC8LGlhms/zcnzXT6wduvp4grOOafL3z/Q3gPqXAqbKwW/JVJVoeVA8k2mqDpcy/A/8JigHxWEbEHPgFHXmt3gTwbEn34XR3o3DjIutP5j2f1zXNKFgJQHPKAsiX8nk/1FlVt6gIYdtf15EAWrUelJBS7opYG48tm17XksNQ7MWY3BBx7vsIRVfxlv1ongPl8tuNEgxJU3EsD9zI8HaTLEdIsGZGsxnsVJCZyxgNf/Vt4uiTlpTZyugKpxsFiPSJ7G94Q+GqouXediac+NUnoXR8SS60tchN0EfrSM+fz/7aUTl3fS4Buk6b+b0IwAKMWNqlZs13FuPbgVuF02hWij4y24AY/mgihN0ZHEdzDTJXbrL8FrNfBzpTA6uwusDu7QflirsZdz7lBj1uIkD48t3Gw6af/s8crRxqQo0Da2hZeKVYXpx5kUDap5VS3TbEp9Rc6+nDNIxrKu2x85gizA38x2siFrvBbseGvDdU1/ODjkeL9qgsy/tCc6rC8TiAlBUWgQ2pffJox4SYo4nSKawH8FIa5gWu9kCsejaNX+AucvDgekuYGwFBxfH+Gl031l2LV6CaE4EDBnDIFgF/J3td8t8mrPFuAYadLydcFV4JCS5+FeFOyLD4Eng9K0ZZo7J4q2iS/EZsuyZiniueahPF/7HfJSHiVnoXg/h4=
deploy:
  provider: heroku
  api_key:
    secure: loghgBWu5wAYLBhh+zW0LCQa/KelXndBCBPJmKa+xdOvtDEruaMl539EGVMN0zwxQNxM38MC97ZDy8V0mXJK75kwfoMAhIoloSzTSKaTWFQdOU3lzZaoN+5rg5ofG8mSpxoP/1EXm/Fz5DMCdt9JJaYzdIBnpiJiutHzzUKfsJh2Em07RgjVxUPT/HuopsV8RR86PZOA4Eg8mUtbRguoN0IsrOMO+KPN1zV7NlhogOOEDhFh77OIn5PfXe4A5Tf4SfPySvXpU11hsJlcttxpoXGAVsdjWOqWy8j1xWkPSxb92RJjnirRJKb9tZ+DVRpu3YCl8dbBQTZmXaIe0TU6IHpcupwJ0M4Ju32eJE0sHJ0Z97F0lRQfrQxhW6unJNgJ+EVTQt+Xk+T+jE13z3e3h0obqnP99ylF91O357SumTI344JNqsKB0VKDT00K3wjHjIiVIaRcHl7yfRJtlBItjiupwfPWF5jeHh2sAAKRsu2DLtDzwMbDeWu5SB1JBSTVExNwcZTx+TGohMJrRpfS4pcZv8EHjkkkOEOJAEt7hPumXTSaW1nWnxfJztoAE6QIwE2wHyUtEyM1MrAK9CCA//Q4GHM1ZWvmB2pam+sNQD9d44XbU5fEwt4NY/XzSWFZeao7xx1l1M2MM9i97u3gpe6sxjF4eMK2iSANrog1JPA=
  app: ci_try
  on:
    repo: alejandrotoro/ci_try
  run:
    - "rails db:migrate"