default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: ci_try_development
  username: alejandro
  password: '3105979727'
  host: localhost
  port: 5432

test: &test
  <<: *default
  database: ci_try_test
  username: alejandro
  password: '3105979727'
  host: localhost
  port: 5432

cucumber:
  <<: *test
